# Generated by Django 5.1 on 2024-09-26 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_couser',
            name='core_subject',
        ),
    ]
