# Generated by Django 5.1 on 2024-09-27 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_usercourse'),
    ]

    operations = [
        migrations.CreateModel(
            name='helpquary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=500)),
                ('student_email', models.CharField(max_length=300)),
                ('student_message', models.TextField()),
            ],
        ),
    ]
