# Generated by Django 5.1 on 2024-11-06 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_helpquary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercourse',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
