# Generated by Django 5.0.6 on 2024-08-15 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_sign_up_table_update_date_alter_sign_up_table_add_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sign_up_table',
            name='pincode',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sign_up_table',
            name='profile_pic',
            field=models.ImageField(blank=True, default='photo', null=True, upload_to='profiles'),
        ),
    ]
