# Generated by Django 5.0.6 on 2024-08-15 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_alter_sign_up_table_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sign_up_table',
            name='pincode',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
    ]
