# Generated by Django 5.0.6 on 2024-08-15 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_alter_sign_up_table_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sign_up_table',
            name='pincode',
            field=models.CharField(blank=True, default='0', max_length=120, null=True),
        ),
    ]
