# Generated by Django 5.0.6 on 2024-08-15 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_alter_sign_up_table_pincode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sign_up_table',
            name='p_email',
        ),
    ]
