# Generated by Django 5.1 on 2024-09-24 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_remove_course_slug_course_new_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='info',
            field=models.TextField(),
        ),
    ]
