# Generated by Django 5.1 on 2024-09-26 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_course_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_info',
            name='about_course',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='course_info',
            name='chapter1',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='course_info',
            name='chapter2',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='course_info',
            name='chapter3',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='course_info',
            name='chapter4',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='course_info',
            name='chapter5',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='course_info',
            name='level',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='course_info',
            name='rating',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
