# Generated by Django 5.1 on 2024-09-26 05:25

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_course_info_about_course_course_info_chapter1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_info',
            name='temp',
            field=autoslug.fields.AutoSlugField(default=None, null=True, primary_key=None, unique=True),
        ),
    ]
