# Generated by Django 5.1 on 2024-09-26 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_course_info_temp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course_info',
            name='main_course',
        ),
        migrations.RemoveField(
            model_name='course_info',
            name='temp',
        ),
    ]
