# Generated by Django 5.1 on 2024-09-26 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_remove_course_info_main_course_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='course_info',
        ),
        migrations.AddField(
            model_name='course',
            name='about_course',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='chapter1',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='chapter2',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='chapter3',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='chapter4',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='chapter5',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='rating',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='teacher_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
