# Generated by Django 5.1 on 2024-09-28 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_sign_up_table_about_me'),
    ]

    operations = [
        migrations.AddField(
            model_name='sign_up_table',
            name='ispaid',
            field=models.BooleanField(default=False),
        ),
    ]
