# Generated by Django 5.1 on 2024-10-29 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_free_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='free_course',
            old_name='theme1',
            new_name='theme',
        ),
        migrations.RenameField(
            model_name='free_course',
            old_name='youtube1',
            new_name='youtube',
        ),
        migrations.RemoveField(
            model_name='free_course',
            name='theme2',
        ),
        migrations.RemoveField(
            model_name='free_course',
            name='theme3',
        ),
        migrations.RemoveField(
            model_name='free_course',
            name='theme4',
        ),
        migrations.RemoveField(
            model_name='free_course',
            name='theme5',
        ),
        migrations.RemoveField(
            model_name='free_course',
            name='youtube2',
        ),
        migrations.RemoveField(
            model_name='free_course',
            name='youtube3',
        ),
        migrations.RemoveField(
            model_name='free_course',
            name='youtube4',
        ),
        migrations.RemoveField(
            model_name='free_course',
            name='youtube5',
        ),
        migrations.AddField(
            model_name='course',
            name='link1',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='link2',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='link3',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='link4',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='link5',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
