# Generated by Django 5.1 on 2024-10-30 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_remove_course_link1_remove_course_link2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='video1',
            field=models.FileField(null=True, upload_to='lecture_video/'),
        ),
        migrations.AddField(
            model_name='course',
            name='video2',
            field=models.FileField(null=True, upload_to='lecture_video/'),
        ),
        migrations.AddField(
            model_name='course',
            name='video3',
            field=models.FileField(null=True, upload_to='lecture_video/'),
        ),
        migrations.AddField(
            model_name='course',
            name='video4',
            field=models.FileField(null=True, upload_to='lecture_video/'),
        ),
        migrations.AddField(
            model_name='course',
            name='video5',
            field=models.FileField(null=True, upload_to='lecture_video/'),
        ),
    ]
