# Generated by Django 5.1 on 2024-10-30 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0040_course_video1_course_video2_course_video3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='video1',
            field=models.FileField(blank=True, null=True, upload_to='lecture_video/'),
        ),
        migrations.AlterField(
            model_name='course',
            name='video2',
            field=models.FileField(blank=True, null=True, upload_to='lecture_video/'),
        ),
        migrations.AlterField(
            model_name='course',
            name='video3',
            field=models.FileField(blank=True, null=True, upload_to='lecture_video/'),
        ),
        migrations.AlterField(
            model_name='course',
            name='video4',
            field=models.FileField(blank=True, null=True, upload_to='lecture_video/'),
        ),
        migrations.AlterField(
            model_name='course',
            name='video5',
            field=models.FileField(blank=True, null=True, upload_to='lecture_video/'),
        ),
    ]
