# Generated by Django 5.1 on 2024-11-06 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0042_course_is_complete_quesmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='is_complete',
        ),
    ]
